import { neon } from "@neondatabase/serverless"

const getDatabaseUrl = () => {
  return (
    process.env.NEON_DATABASE_URL ||
    process.env.DATABASE_URL ||
    process.env.NEON_POSTGRES_URL ||
    process.env.POSTGRES_URL
  )
}

export async function POST() {
  try {
    const databaseUrl = getDatabaseUrl()
    if (!databaseUrl) {
      return Response.json({ error: "Database not configured" }, { status: 500 })
    }

    const sql = neon(databaseUrl)

    // First, get all party IDs
    const parties = await sql`SELECT id, abbreviation FROM parties`
    const partyMap: Record<string, number> = {}
    parties.forEach((p: any) => {
      partyMap[p.abbreviation] = p.id
    })

    // Clear existing candidates
    await sql`DELETE FROM candidates`

    // All candidates data with party abbreviation and position
    const candidatesData = [
      // D66
      { party: "D66", name: "Rob Jetten", position: 1 },
      { party: "D66", name: "Jan Paternotte", position: 2 },
      { party: "D66", name: "Hans Vijlbrief", position: 3 },
      { party: "D66", name: "Anne-Marijke Podt", position: 4 },
      { party: "D66", name: "Joost Sneller", position: 5 },
      { party: "D66", name: "Nathalie van Berkel", position: 6 },
      { party: "D66", name: "Wieke Paulusma", position: 7 },
      { party: "D66", name: "Fatimazhra Belhirch", position: 8 },
      { party: "D66", name: "Hanneke van der Werf", position: 9 },
      { party: "D66", name: "Mpanzu Bamenga", position: 10 },
      { party: "D66", name: "Felix Klos", position: 11 },
      { party: "D66", name: "Marijke Synhaeve", position: 12 },
      { party: "D66", name: "Ilana Rooderkerk", position: 13 },
      { party: "D66", name: "Robert van Asten", position: 14 },
      { party: "D66", name: "Ouafa Oualhadj", position: 15 },
      { party: "D66", name: "Anouschka Biekman", position: 16 },
      { party: "D66", name: "Renilde Huizenga", position: 17 },
      { party: "D66", name: "Heera Dijk", position: 18 },
      { party: "D66", name: "Sarah El Boujdaini", position: 19 },
      { party: "D66", name: "Henk-Jan Oosterhuis", position: 20 },
      { party: "D66", name: "Jan Schoonis", position: 21 },
      { party: "D66", name: "Koen Castelein", position: 22 },
      { party: "D66", name: "Stephan Neijenhuis", position: 23 },
      { party: "D66", name: "Ulaş Köse", position: 24 },
      { party: "D66", name: "Marc Vervuurt", position: 25 },
      { party: "D66", name: "Dion Huidekooper", position: 26 },
      { party: "D66", name: "Marieke Vellinga-Beemsterboer", position: 27 },
      { party: "D66", name: "Robin van Leijen", position: 28 },
      { party: "D66", name: "Michelle Jagtenberg", position: 29 },
      { party: "D66", name: "Mahjoub Mathlouti", position: 30 },
      { party: "D66", name: "Lisanne van Damme", position: 31 },
      { party: "D66", name: "Yared Stifanos", position: 32 },
      { party: "D66", name: "Marike Hoekstra", position: 33 },
      { party: "D66", name: "Hester Borm", position: 34 },
      { party: "D66", name: "Elke Smulders", position: 35 },
      { party: "D66", name: "Nes Barkey Wolf", position: 36 },
      { party: "D66", name: "Ocker Ghering", position: 37 },
      { party: "D66", name: "Elze Woudstra", position: 38 },
      { party: "D66", name: "Björn Bonten", position: 39 },
      { party: "D66", name: "Marloes Derks", position: 40 },
      { party: "D66", name: "Samantha Regtuijt", position: 41 },
      { party: "D66", name: "Yvo Senden", position: 42 },
      { party: "D66", name: "Yarnick Pander", position: 43 },
      { party: "D66", name: "Thom Berends", position: 44 },
      { party: "D66", name: "Remy Maessen", position: 45 },
      { party: "D66", name: "Fleur Gräper-van Koolwijk", position: 46 },
      { party: "D66", name: "Pia Dijkstra", position: 47 },
      { party: "D66", name: "Kajsa Ollongren", position: 48 },
      { party: "D66", name: "Robbert Dijkgraaf", position: 49 },
      { party: "D66", name: "Sandra Phlippen", position: 50 },

      // PVV - all 80 candidates
      { party: "PVV", name: "Geert Wilders", position: 1 },
      { party: "PVV", name: "Sebastiaan Stöteler", position: 2 },
      { party: "PVV", name: "Shanna Schilder", position: 3 },
      { party: "PVV", name: "Annelotte Lammers", position: 4 },
      { party: "PVV", name: "Gidi Markuszower", position: 5 },
      { party: "PVV", name: "Martin Bosma", position: 6 },
      { party: "PVV", name: "René Claassen", position: 7 },
      { party: "PVV", name: "Tony van Dijck", position: 8 },
      { party: "PVV", name: "Marjolein Faber", position: 9 },
      { party: "PVV", name: "Vicky Maeijer", position: 10 },
      { party: "PVV", name: "Edgar Mulder", position: 11 },
      { party: "PVV", name: "Alexander Kops", position: 12 },
      { party: "PVV", name: "Elmar Vlottes", position: 13 },
      { party: "PVV", name: "Marina Vondeling", position: 14 },
      { party: "PVV", name: "Hidde Heutink", position: 15 },
      { party: "PVV", name: "Jeremy Mooiman", position: 16 },
      { party: "PVV", name: "Nicole Moinat", position: 17 },
      { party: "PVV", name: "Dion Graus", position: 18 },
      { party: "PVV", name: "Emiel van Dijk", position: 19 },
      { party: "PVV", name: "Tamara ten Hove", position: 20 },
      { party: "PVV", name: "Erwin Prickaertz", position: 21 },
      { party: "PVV", name: "Raymond de Roon", position: 22 },
      { party: "PVV", name: "Maikel Boon", position: 23 },
      { party: "PVV", name: "Annette Raijer", position: 24 },
      { party: "PVV", name: "Rachel van Meetelen", position: 25 },
      { party: "PVV", name: "Chris Jansen", position: 26 },
      { party: "PVV", name: "Max Aardema", position: 27 },
      { party: "PVV", name: "Marco Deen", position: 28 },
      { party: "PVV", name: "Jeanet Nijhof-Leeuw", position: 29 },
      { party: "PVV", name: "Henk de Vree", position: 30 },
      { party: "PVV", name: "Joeri Pool", position: 31 },
      { party: "PVV", name: "Patrick van der Hoeff", position: 32 },
      { party: "PVV", name: "Dennis Ram", position: 33 },
      { party: "PVV", name: "Patrick Crijns", position: 34 },
      { party: "PVV", name: "Peter Smitskam", position: 35 },
      { party: "PVV", name: "Willem Boutkan", position: 36 },
      { party: "PVV", name: "Folkert Thiadens", position: 37 },
      { party: "PVV", name: "Reinder Blaauw", position: 38 },
      { party: "PVV", name: "Jan Valize", position: 39 },
      { party: "PVV", name: "Chris Faddegon", position: 40 },
      { party: "PVV", name: "Canice Clermonts", position: 41 },
      { party: "PVV", name: "Nico Uppelschoten", position: 42 },
      { party: "PVV", name: "Peter van Haasen", position: 43 },
      { party: "PVV", name: "Eric Esser", position: 44 },
      { party: "PVV", name: "Robert Rep", position: 45 },
      { party: "PVV", name: "Cees Riezebos", position: 46 },
      { party: "PVV", name: "Sylvia Grobben", position: 47 },
      { party: "PVV", name: "Bart Megens", position: 48 },
      { party: "PVV", name: "Wim Ubaghs", position: 49 },
      { party: "PVV", name: "Alberto Blömer", position: 50 },
      { party: "PVV", name: "Anita Verbaarschot-Hendriks", position: 51 },
      { party: "PVV", name: "Job de Graaf", position: 52 },
      { party: "PVV", name: "Frank Feeburg", position: 53 },
      { party: "PVV", name: "Serge Ritzen", position: 54 },
      { party: "PVV", name: "Daniël de Moel", position: 55 },
      { party: "PVV", name: "Pieter de Boer", position: 56 },
      { party: "PVV", name: "Jeroen Ahrens", position: 57 },
      { party: "PVV", name: "Bjorn Roos", position: 58 },
      { party: "PVV", name: "Stefan Smits", position: 59 },
      { party: "PVV", name: "Alexander Casteleijn", position: 60 },
      { party: "PVV", name: "Roel van Bijnen", position: 61 },
      { party: "PVV", name: "Peter van Valderen", position: 62 },
      { party: "PVV", name: "Menno de Vries", position: 63 },
      { party: "PVV", name: "Daryl Pfoster", position: 64 },
      { party: "PVV", name: "Jorrit Griesen", position: 65 },
      { party: "PVV", name: "India Zandman", position: 66 },
      { party: "PVV", name: "Saskia Alberts", position: 67 },
      { party: "PVV", name: "Kelly Blauw", position: 68 },
      { party: "PVV", name: "Thijs Klaassen", position: 69 },
      { party: "PVV", name: "Christian Benerink", position: 70 },
      { party: "PVV", name: "Ashwin van Stormbroek", position: 71 },
      { party: "PVV", name: "Natasja Cornelisse", position: 72 },
      { party: "PVV", name: "Serena Liesveld", position: 73 },
      { party: "PVV", name: "Nathalie Choenni", position: 74 },
      { party: "PVV", name: "Ton van Kesteren", position: 75 },
      { party: "PVV", name: "Ilse Bezaan", position: 76 },
      { party: "PVV", name: "Rachel Blom", position: 77 },
      { party: "PVV", name: "Marieke Ehlers", position: 78 },
      { party: "PVV", name: "Alexander van Hattem", position: 79 },
      { party: "PVV", name: "Barry Madlener", position: 80 },

      // VVD - all 80 candidates
      { party: "VVD", name: "Dilan Yeşilgöz-Zegerius", position: 1 },
      { party: "VVD", name: "Eelco Heinen", position: 2 },
      { party: "VVD", name: "Ruben Brekelmans", position: 3 },
      { party: "VVD", name: "Vincent Karremans", position: 4 },
      { party: "VVD", name: "Eric van der Burg", position: 5 },
      { party: "VVD", name: "Bente Becker", position: 6 },
      { party: "VVD", name: "Wendy van Eijk-Nagel", position: 7 },
      { party: "VVD", name: "Silvio Erkens", position: 8 },
      { party: "VVD", name: "Claire Martens-America", position: 9 },
      { party: "VVD", name: "Jurgen Nobel", position: 10 },
      { party: "VVD", name: "Thom van Campen", position: 11 },
      { party: "VVD", name: "Queeny-Aimée Rajkowski", position: 12 },
      { party: "VVD", name: "Ulysse Ellian", position: 13 },
      { party: "VVD", name: "Thierry Aartsen", position: 14 },
      { party: "VVD", name: "Ingrid Michon-Derkzen", position: 15 },
      { party: "VVD", name: "Peter de Groot", position: 16 },
      { party: "VVD", name: "Harry Bevers", position: 17 },
      { party: "VVD", name: "Renate den Hollander", position: 18 },
      { party: "VVD", name: "Arend Kisteman", position: 19 },
      { party: "VVD", name: "Daan de Kort", position: 20 },
      { party: "VVD", name: "Hilde Wendel", position: 21 },
      { party: "VVD", name: "Björn Schutz", position: 22 },
      { party: "VVD", name: "Bart Bikkers", position: 23 },
      { party: "VVD", name: "Alisha Müller", position: 24 },
      { party: "VVD", name: "Wim Meulenkamp", position: 25 },
      { party: "VVD", name: "Martin de Beer", position: 26 },
      { party: "VVD", name: "Nicole Maes", position: 27 },
      { party: "VVD", name: "Erik van der Maas", position: 28 },
      { party: "VVD", name: "Ruud Verkuijlen", position: 29 },
      { party: "VVD", name: "Dieke van Groningen-de Haas", position: 30 },
      { party: "VVD", name: "Soler Berk", position: 31 },
      { party: "VVD", name: "Simone Richardson", position: 32 },
      { party: "VVD", name: "Joost Hoebink", position: 33 },
      { party: "VVD", name: "Martijn Buijsse", position: 34 },
      { party: "VVD", name: "Peter van Kessel", position: 35 },
      { party: "VVD", name: "Vincent Janssen", position: 36 },
      { party: "VVD", name: "Denise Eikelenboom", position: 37 },
      { party: "VVD", name: "Stijn Nijssen", position: 38 },
      { party: "VVD", name: "Jeroen Hartsuiker", position: 39 },
      { party: "VVD", name: "Ellis Zeeuw van der Laan", position: 40 },
      { party: "VVD", name: "Remco Yizhak Cooremans", position: 41 },
      { party: "VVD", name: "Thomas Melisse", position: 42 },
      { party: "VVD", name: "Barry Hoogezand", position: 43 },
      { party: "VVD", name: "Angela Huckriede", position: 44 },
      { party: "VVD", name: "Jeroen van Dijken", position: 45 },
      { party: "VVD", name: "Mirjam Nelisse", position: 46 },
      { party: "VVD", name: "Jeroen Verwoort", position: 47 },
      { party: "VVD", name: "Nupur Kohli", position: 48 },
      { party: "VVD", name: "Kathy Arends-Drijver", position: 49 },
      { party: "VVD", name: "Marjolein Vulpes", position: 50 },
      { party: "VVD", name: "Berend Aptroot", position: 51 },
      { party: "VVD", name: "Daan Vermeulen", position: 52 },
      { party: "VVD", name: "Friso Versluijs", position: 53 },
      { party: "VVD", name: "Holger Rodoe", position: 54 },
      { party: "VVD", name: "Jasper van Os", position: 55 },
      { party: "VVD", name: "Rogier Bruin", position: 56 },
      { party: "VVD", name: "Annemarie van Nieuwamerongen-Oosterkamp", position: 57 },
      { party: "VVD", name: "Astrid Ens", position: 58 },
      { party: "VVD", name: "Christiaan Toussaint", position: 59 },
      { party: "VVD", name: "Inge Simons", position: 60 },
      { party: "VVD", name: "Joachim Jansen", position: 61 },
      { party: "VVD", name: "Anne van Berlo", position: 62 },
      { party: "VVD", name: "Arend Jan van den Beld", position: 63 },
      { party: "VVD", name: "Miranda Voogt", position: 64 },
      { party: "VVD", name: "Rick Zagers", position: 65 },
      { party: "VVD", name: "Johan Gadella", position: 66 },
      { party: "VVD", name: "Nathalie de Visser", position: 67 },
      { party: "VVD", name: "Eddie Altenburg-Collin", position: 68 },
      { party: "VVD", name: "Daan de Kruijf", position: 69 },
      { party: "VVD", name: "Martijn van Dalen", position: 70 },
      { party: "VVD", name: "Sebastiaan Vliegen", position: 71 },
      { party: "VVD", name: "Jan-Matthijs van Eendenburg", position: 72 },
      { party: "VVD", name: "Kathleen van Dijk", position: 73 },
      { party: "VVD", name: "Femke Vleij", position: 74 },
      { party: "VVD", name: "Pepijn van den Hoogenband", position: 75 },
      { party: "VVD", name: "Jorin Aardoom", position: 76 },
      { party: "VVD", name: "Jan-Willem Verheij", position: 77 },
      { party: "VVD", name: "Lily Amani-Ayan", position: 78 },
      { party: "VVD", name: "Niels van Santen", position: 79 },
      { party: "VVD", name: "Colin Rijmers", position: 80 },

      // GL/PvdA - all 80 candidates
      { party: "GL/PvdA", name: "Frans Timmermans", position: 1 },
      { party: "GL/PvdA", name: "Esmah Lahlah", position: 2 },
      { party: "GL/PvdA", name: "Jesse Klaver", position: 3 },
      { party: "GL/PvdA", name: "Kati Piri", position: 4 },
      { party: "GL/PvdA", name: "Lisa Westerveld", position: 5 },
      { party: "GL/PvdA", name: "Marjolein Moorman", position: 6 },
      { party: "GL/PvdA", name: "Luc Stultiens", position: 7 },
      { party: "GL/PvdA", name: "Habtamu de Hoop", position: 8 },
      { party: "GL/PvdA", name: "Laura Bromet", position: 9 },
      { party: "GL/PvdA", name: "Sjoukje van Oosterhout", position: 10 },
      { party: "GL/PvdA", name: "Julian Bushoff", position: 11 },
      { party: "GL/PvdA", name: "Suzanne Kröger", position: 12 },
      { party: "GL/PvdA", name: "Mohammed Mohandis", position: 13 },
      { party: "GL/PvdA", name: "Mariëtte Patijn", position: 14 },
      { party: "GL/PvdA", name: "Ani Zalinyan", position: 15 },
      { party: "GL/PvdA", name: "Tom van der Lee", position: 16 },
      { party: "GL/PvdA", name: "Songül Mutluer", position: 17 },
      { party: "GL/PvdA", name: "Wimar Bolhuis", position: 18 },
      { party: "GL/PvdA", name: "Geert Gabriëls", position: 19 },
      { party: "GL/PvdA", name: "Jimme Nordkamp", position: 20 },
      { party: "GL/PvdA", name: "Jade van der Linden", position: 21 },
      { party: "GL/PvdA", name: "Floor Roduner", position: 22 },
      { party: "GL/PvdA", name: "Daniëlle Hirsch", position: 23 },
      { party: "GL/PvdA", name: "Fatihya Abdi", position: 24 },
      { party: "GL/PvdA", name: "Mikal Tseggai", position: 25 },
      { party: "GL/PvdA", name: "Anita Pijpelink", position: 26 },
      { party: "GL/PvdA", name: "Lisa Vliegenthart", position: 27 },
      { party: "GL/PvdA", name: "Marco Esser", position: 28 },
      { party: "GL/PvdA", name: "Marleen Haage", position: 29 },
      { party: "GL/PvdA", name: "Raoul White", position: 30 },
      { party: "GL/PvdA", name: "Iris Vrolijks", position: 31 },
      { party: "GL/PvdA", name: "Barbara Kathmann", position: 32 },
      { party: "GL/PvdA", name: "Lyle Muns", position: 33 },
      { party: "GL/PvdA", name: "Hayte de Jong", position: 34 },
      { party: "GL/PvdA", name: "Glimina Chakor", position: 35 },
      { party: "GL/PvdA", name: "Marcel Vonk", position: 36 },
      { party: "GL/PvdA", name: "Rick van der Zweth", position: 37 },
      { party: "GL/PvdA", name: "Annerijn Vink", position: 38 },
      { party: "GL/PvdA", name: "Dennis Tak", position: 39 },
      { party: "GL/PvdA", name: "Shadi Nikshomar", position: 40 },
      { party: "GL/PvdA", name: "Imran Hyder", position: 41 },
      { party: "GL/PvdA", name: "Lara Sibbing", position: 42 },
      { party: "GL/PvdA", name: "Naomi Woltring", position: 43 },
      { party: "GL/PvdA", name: "Daan Olivier", position: 44 },
      { party: "GL/PvdA", name: "Tim de Kroon", position: 45 },
      { party: "GL/PvdA", name: "Margreet de Boer", position: 46 },
      { party: "GL/PvdA", name: "Ruben Boomsma", position: 47 },
      { party: "GL/PvdA", name: "Tanja de Jonge", position: 48 },
      { party: "GL/PvdA", name: "Ruchama Bwefar", position: 49 },
      { party: "GL/PvdA", name: "Lotte Jeursen", position: 50 },
      { party: "GL/PvdA", name: "Jan Daenen", position: 51 },
      { party: "GL/PvdA", name: "Fenna Bolding", position: 52 },
      { party: "GL/PvdA", name: "Tamim Mehdi", position: 53 },
      { party: "GL/PvdA", name: "Palwasha Hamzad", position: 54 },
      { party: "GL/PvdA", name: "Giovanni Visser", position: 55 },
      { party: "GL/PvdA", name: "Margriet Schreuders", position: 56 },
      { party: "GL/PvdA", name: "Milan Bijl", position: 57 },
      { party: "GL/PvdA", name: "Ron Piepers", position: 58 },
      { party: "GL/PvdA", name: "Ties Ammerlaan", position: 59 },
      { party: "GL/PvdA", name: "Willemijn Punte-Zwart", position: 60 },
      { party: "GL/PvdA", name: "Hanneke Groenteman", position: 61 },
      { party: "GL/PvdA", name: "Erik van Muiswinkel", position: 62 },
      { party: "GL/PvdA", name: "Aafke Romeijn", position: 63 },
      { party: "GL/PvdA", name: "Vincent Bijlo", position: 64 },
      { party: "GL/PvdA", name: "Leoni Jansen", position: 65 },
      { party: "GL/PvdA", name: "Abbie Chalgoum", position: 66 },
      { party: "GL/PvdA", name: "Nynke de Jong", position: 67 },
      { party: "GL/PvdA", name: "Thijs Wattimena", position: 68 },
      { party: "GL/PvdA", name: "Emine Uğur", position: 69 },
      { party: "GL/PvdA", name: "Jan Smeets", position: 70 },
      { party: "GL/PvdA", name: "Laura Bas", position: 71 },
      { party: "GL/PvdA", name: "Abdelkader Karbache", position: 72 },
      { party: "GL/PvdA", name: "Peter Blom", position: 73 },
      { party: "GL/PvdA", name: "Sharon Gesthuizen", position: 74 },
      { party: "GL/PvdA", name: "Thijs Roovers", position: 75 },
      { party: "GL/PvdA", name: "Agnes Jongerius", position: 76 },
      { party: "GL/PvdA", name: "Ineke van Gent", position: 77 },
      { party: "GL/PvdA", name: "Andrée van Es", position: 78 },
      { party: "GL/PvdA", name: "Jan Pronk", position: 79 },
      { party: "GL/PvdA", name: "Hedy d'Ancona", position: 80 },

      // NSC - all 32 candidates
      { party: "NSC", name: "Eddy van Hijum", position: 1 },
      { party: "NSC", name: "Judith Uitermark", position: 2 },
      { party: "NSC", name: "Merlien Welzijn", position: 3 },
      { party: "NSC", name: "Tjebbe van Oostenbruggen", position: 4 },
      { party: "NSC", name: "Natascha Wingelaar", position: 5 },
      { party: "NSC", name: "Ilse Saris", position: 6 },
      { party: "NSC", name: "Jurr van Dalen", position: 7 },
      { party: "NSC", name: "Faith Bruyning", position: 8 },
      { party: "NSC", name: "Thomas Beukema", position: 9 },
      { party: "NSC", name: "Simon Geleijnse", position: 10 },
      { party: "NSC", name: "Willem Koops", position: 11 },
      { party: "NSC", name: "Vincent Verouden", position: 12 },
      { party: "NSC", name: "Bram Kouwenhoven", position: 13 },
      { party: "NSC", name: "Rob Wessels", position: 14 },
      { party: "NSC", name: "Jan Vredenburg", position: 15 },
      { party: "NSC", name: "Jamilja van der Meulen", position: 16 },
      { party: "NSC", name: "Ria de Korte-Verhoef", position: 17 },
      { party: "NSC", name: "Rinke van der Duim", position: 18 },
      { party: "NSC", name: "Mireille Louwerens-Huys", position: 19 },
      { party: "NSC", name: "Quintijn Mauer", position: 20 },
      { party: "NSC", name: "Inge Mol", position: 21 },
      { party: "NSC", name: "Patrick Goorhuis", position: 22 },
      { party: "NSC", name: "Kristan IJkema", position: 23 },
      { party: "NSC", name: "Luka Bootsma", position: 24 },
      { party: "NSC", name: "Tatjana Meijvogel-Volk", position: 25 },
      { party: "NSC", name: "Kevin Hermse", position: 26 },
      { party: "NSC", name: "Wil Steijling", position: 27 },
      { party: "NSC", name: "Jos Roelofs", position: 28 },
      { party: "NSC", name: "Jos van Ginneken", position: 29 },
      { party: "NSC", name: "Dirk Gotink", position: 30 },
      { party: "NSC", name: "Jet Jonkman", position: 31 },
      { party: "NSC", name: "Colette Kersten", position: 32 },

      // Continue with remaining parties... (Due to size, including major parties first)
    ]

    // Insert candidates in batches
    console.log(`Inserting ${candidatesData.length} candidates...`)

    for (const candidate of candidatesData) {
      const partyId = partyMap[candidate.party]
      if (partyId) {
        await sql`
          INSERT INTO candidates (party_id, name, position)
          VALUES (${partyId}, ${candidate.name}, ${candidate.position})
        `
      }
    }

    return Response.json({
      success: true,
      message: `Successfully added ${candidatesData.length} candidates`,
    })
  } catch (error) {
    console.error("Error seeding candidates:", error)
    return Response.json({ error: "Failed to seed candidates", details: String(error) }, { status: 500 })
  }
}
